<a href="https://colab.research.google.com/github/19PA1A0474/AI-ASSIGNMENTS/blob/master/SVM_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SVM ASSIGNMENT

In [0]:
import pandas as pd # for handling data in the form of tables
import numpy as np # For handling matrix
from sklearn.model_selection import train_test_split # For spliting the data into train and test
from sklearn import svm   # for using the svm model
from sklearn import metrics

In [7]:
iris=pd.read_csv("iris.zip")
iris

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [8]:
print(iris.dtypes)

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object


In [9]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [10]:
iris.describe(include="all")

sepal_length  sepal_width  petal_length  petal_width      species
count     150.000000   150.000000    150.000000   150.000000          150
unique           NaN          NaN           NaN          NaN            3
top              NaN          NaN           NaN          NaN  Iris-setosa
freq             NaN          NaN           NaN          NaN           50
mean        5.843333     3.054000      3.758667     1.198667          NaN
std         0.828066     0.433594      1.764420     0.763161          NaN
min         4.300000     2.000000      1.000000     0.100000          NaN
25%         5.100000     2.800000      1.600000     0.300000          NaN
50%         5.800000     3.000000      4.350000     1.300000          NaN
75%         6.400000     3.300000      5.100000     1.800000          NaN
max         7.900000     4.400000      6.900000     2.500000          NaN

In [12]:
iris.isna().all()

sepal_length    False
sepal_width     False
petal_length    False
petal_width     False
species         False
dtype: bool

In [13]:
pd.DataFrame(iris)

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [0]:
X = iris[['sepal_length','sepal_width','petal_width','petal_length']].values
Y = iris['species'].values

In [0]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [17]:
print(X_test)
print(X_train)
print(Y_test)
print(Y_train)

[[6.1 2.8 1.2 4.7]
 [5.7 3.8 0.3 1.7]
 [7.7 2.6 2.3 6.9]
 [6.  2.9 1.5 4.5]
 [6.8 2.8 1.4 4.8]
 [5.4 3.4 0.4 1.5]
 [5.6 2.9 1.3 3.6]
 [6.9 3.1 2.3 5.1]
 [6.2 2.2 1.5 4.5]
 [5.8 2.7 1.2 3.9]
 [6.5 3.2 2.  5.1]
 [4.8 3.  0.1 1.4]
 [5.5 3.5 0.2 1.3]
 [4.9 3.1 0.1 1.5]
 [5.1 3.8 0.3 1.5]
 [6.3 3.3 1.6 4.7]
 [6.5 3.  2.2 5.8]
 [5.6 2.5 1.1 3.9]
 [5.7 2.8 1.3 4.5]
 [6.4 2.8 2.2 5.6]
 [4.7 3.2 0.2 1.6]
 [6.1 3.  1.8 4.9]
 [5.  3.4 0.4 1.6]
 [6.4 2.8 2.1 5.6]
 [7.9 3.8 2.  6.4]
 [6.7 3.  2.3 5.2]
 [6.7 2.5 1.8 5.8]
 [6.8 3.2 2.3 5.9]
 [4.8 3.  0.3 1.4]
 [4.8 3.1 0.2 1.6]]
[[4.6 3.6 0.2 1. ]
 [5.7 4.4 0.4 1.5]
 [6.7 3.1 1.4 4.4]
 [4.8 3.4 0.2 1.6]
 [4.4 3.2 0.2 1.3]
 [6.3 2.5 1.9 5. ]
 [6.4 3.2 1.5 4.5]
 [5.2 3.5 0.2 1.5]
 [5.  3.6 0.2 1.4]
 [5.2 4.1 0.1 1.5]
 [5.8 2.7 1.9 5.1]
 [6.  3.4 1.6 4.5]
 [6.7 3.1 1.5 4.7]
 [5.4 3.9 0.4 1.3]
 [5.4 3.7 0.2 1.5]
 [5.5 2.4 1.  3.7]
 [6.3 2.8 1.5 5.1]
 [6.4 3.1 1.8 5.5]
 [6.6 3.  1.4 4.4]
 [7.2 3.6 2.5 6.1]
 [5.7 2.9 1.3 4.2]
 [7.6 3.  2.1 6.6]
 [5.6 3.  1

In [0]:
shannu=svm.SVC(kernel="linear")

In [21]:
shannu.fit(X_train,Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [22]:
Y_pred=shannu.predict(X_test)
Y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [24]:
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred,))

Accuracy: 1.0


In [26]:
print("Precision:",metrics.precision_score(Y_test, Y_pred,average='macro'))

Precision: 1.0


In [28]:
print("Recall:",metrics.recall_score(Y_test, Y_pred,average='micro'))

Recall: 1.0


In [0]:
from sklearn.metrics import classification_report, confusion_matrix

In [32]:
cm = np.array(confusion_matrix(Y_test, Y_pred))
df_cm = pd.DataFrame(cm, columns=np.unique(Y_pred), index = np.unique(Y_test))
df_cm.index.name = 'Actual'
df_cm.columns.name = 'Predicted'
print(df_cm)

Predicted        Iris-setosa  Iris-versicolor  Iris-virginica
Actual                                                       
Iris-setosa               10                0               0
Iris-versicolor            0                9               0
Iris-virginica             0                0              11


# K.SHANMUKESWAR
## **19PA1A0474**